### ISSUE TITLE
OsiGlpk: check whether time limit has been reached

### ISSUE THREAD

**Issue by svigerske** [coin-or/Osi#35]
Issue created by migration from Trac.

Original creator: @svigerske

Original creation time: 2007-06-18 13:45:29

Assignee: @mjsaltzman

Version: 0.95

Hi,

for GLPK it is possible to impose a timelimit, and it would be nice, when it could be checked via the Osi/GLPK interface, whether GLPK stopped because the timelimit was hit.
So my suggestion is to add a method `isTimeLimitReached()` similar to `isIterationLimitReached()` to the OsiGlpkSolverInterface.
To keep everything compatible with the general OsiSolverInterface class, isAbandoned() could still report true in this case.

Find attached a patch file which can be applied to OsiGlpk rev. 982 and adds this feature.

Best,

Stefan

**Comment by svigerske** [comment]
Attachment [osiglpk.patch](https://www.coin-or.org/issue-attachments/Osi/ticket35/osiglpk.patch) by @svigerske created at 2007-06-18 13:46:34

adding isTimeLimitReached method and member to OsiGlpk...

**Comment by svigerske** [comment]
Comment by @svigerske created at 2007-07-29 15:00:59

Updating my attached file is failing (see below).
So let me just note that an updated patch file which works with OsiGlpk rev. 1033 is available
[here](https://projects.coin-or.org/GAMSlinks/browser/trunk/osiglpk.patch).

Here is the error I get when I try to replace my last attachment:
```
Traceback (most recent call last):
  File "/usr/lib/python2.3/site-packages/trac/web/main.py", line 406, in dispatch_request
    dispatcher.dispatch(req)
  File "/usr/lib/python2.3/site-packages/trac/web/main.py", line 237, in dispatch
    resp = chosen_handler.process_request(req)
  File "/usr/lib/python2.3/site-packages/trac/attachment.py", line 361, in process_request
    self._do_save(req, attachment)
  File "/usr/lib/python2.3/site-packages/trac/attachment.py", line 496, in _do_save
    attachment.insert(filename, upload.file, size)
  File "/usr/lib/python2.3/site-packages/trac/attachment.py", line 183, in insert
    filename))
  File "/usr/lib/python2.3/site-packages/trac/util/__init__.py", line 112, in create_unique_file
    raise Exception('Failed to create unique name: ' + path)
Exception: Failed to create unique name: /home/coin/Trac/Projects/Osi/attachments/ticket/35/osiglpk.100.patch
```

**Comment by svigerske** [comment]
Comment by @svigerske created at 2007-09-23 12:19:59

Also a method the check whether a feasible point has been found in case that the time or iteration limit had been hit would be useful.
I've included this into [my patch](https://projects.coin-or.org/GAMSlinks/browser/trunk/osiglpk.patch) which works with OsiGlpk rev. 1081.

Best,
Stefan

**Comment by svigerske** [comment]
Comment by @LouHafer created at 2008-01-08 00:32:01

Changes committed by Stefan Vigerske.

**Comment by svigerske** [comment]
Comment by @LouHafer created at 2008-01-08 00:32:01

Resolution: fixed
